# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: dawnkylin
subtitle: 想自由
description: 记录一切值得记录的东西
keywords: 博客,笔记,个人生活,程序开发,编程,学习,计算机,操作系统,数据库,前端,后端,JavaScript,NodeJS,Vue,React,TypeScript
author: dawnkylin
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://dawnkylin.github.io/hexo-butterfly-blog
root: /hexo-butterfly-blog/
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc16 #算法： crc16(default) and crc32
  rep: dec #进制： dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - BingSiteAuth.xml

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: false
  auto_detect: true
  tab_replace: ""
  wrap: true
  hljs: false
  exclude_languages: ["mermaid"]
prismjs:
  preprocess: true
  line_number: false
  tab_replace: ""
  exclude_languages: ["mermaid"]

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# 用于 hexo-deployer-git
# deploy:
#   type: git
#   repo:
#     github: git@github.com:dawnkylin/hexo-butterfly-blog.git  # SSH 地址（推荐）
#     # 或 HTTPS 地址：https://github.com/你的用户名/你的仓库名.git
#   branch: gh-pages  # 部署到 gh-pages 分支

markdown:
  plugins:
    - "@renbaoshuo/markdown-it-katex"

search:
  path: search.xml
  field: post
  content: true
  # template: ./search.xml

nofollow:
  enable: true
  # field - The scope you want the plugin to proceed, can be 'site' or 'post'. Default value is site.
  # 'post' - Only add nofollow attribute to external links in your post content
  # 'site' - Add nofollow attribute to external links of whole sites
  field: site
  exclude:
    # - 'exclude1.com'
    # - 'exclude2.com'

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

sitemap:
  path: sitemap.xml

# 由于需要全局都插入 aplayer 和 meting 资源，为了防止插入重复的资源，需要把 asset_inject 设为 false
aplayer:
  meting: true
  asset_inject: false

douban:
  # 你的豆瓣 ID(纯数字格式，不是自定义的域名)。
  id: 238501646
  # 是否将hexo douban命令默认嵌入进hexo g、hexo s，使其自动执行hexo douban 命令
  builtin: false
  # 豆瓣页面是否在访问时实时请求接口。默认为 false，表示页面信息会在执行 hexo douban 命令时更新，优点是生成的页面不会受到后续接口可用性的影响，缺点是需要手动更新。如果设置为 true ，则会在页面访问时实时调用接口进行渲染，无需执行 hexo douban 命令更新页面，但是代价就是如果接口挂了，页面就会G。
  dynamic: true
  # 每页展示的条目数
  item_per_page: 10
  # 每个条目展示的详细信息的最大行数，超过该行数则会以 "..." 省略
  meta_max_line: 4
  # 自定义布局文件。默认值为 page 。无特别需要，留空即可。若配置为 abcd，则表示指定 //theme/hexo-theme/layout/abcd.ejs 文件渲染豆瓣页面。
  customize_layout: page
  swup: false
  book:
    path: books/index.html
    title: "我的书籍"
    # 写在页面开头的一段话,支持 html 语法，可以为空。
    quote: "读万卷书"
    actions:
      - do
      - wish
      - collect
    # 该页面额外的 Front-matter 配置，参考 Hexo 文档。无特别需要，留空即可。
    option:
  movie:
    path: movies/index.html
    title: "我看的电影"
    quote: "大家也分享下好看的电影吧！"
    actions:
      - do
      - wish
      - collect
    option:
  song:
    path: songs/index.html
    title: "我听的歌"
    quote: "大家也分享下好听的歌吧！"
    actions:
      - do
      - wish
      - collect
    option:

hexo_indexnow:
  count: latest # 数字或者"latest"(=1)
  txt_name: 2d2862fcf88a478fa7fe98a7c3db09c8.txt # 链接文件名
  apikey: 2d2862fcf88a478fa7fe98a7c3db09c8 # 你的apikey
  server: bing # indexnow服务器,可选值有:bing、yandex、indexnow

deploy:
  - type: indexnow_url_submitter
