name: Deploy Hexo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-cli -g

      - name: Generate Files
        run: |
          hexo clean  # 使用 npx 查询命令
          hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GitHub 会在每次 workflow 运行时自动生成一个临时的 GITHUB_TOKEN，专门用于当前仓库的操作
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
